version: "3.8"

services:
  # PHP-сервер
  api:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: book-api
    volumes:
      - ./backend:/var/www/html
    environment:
      - DB_HOST=mysql
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
    depends_on:
      - mysql
    networks:
      - book-network

  # Nginx
  webserver:
    image: nginx:alpine
    container_name: book-webserver
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./backend:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - api
    networks:
      - book-network

  # MySQL
  mysql:
    image: mysql:8.0
    container_name: book-mysql
    environment:
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
    volumes:
      - mysql-data:/var/lib/mysql
      - ./docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
    ports:
      - "3306:3306"
    networks:
      - book-network

  # React приложение
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: book-frontend
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost/api
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - book-network
    stdin_open: true
    tty: true

volumes:
  mysql-data:

networks:
  book-network:
    driver: bridge
